name: Build & Release

on:
  push:
    tags-ignore: [ '*-SNAPSHOT' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: "KzGraph"
          path: "./target/KzGraph*.jar"
      - name: Publish Package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: GH Release
        uses: softprops/action-gh-release@v1
        with:
          body: "New release of KzGraph"
          fail_on_unmatched_files: true
          files: "./target/KzGraph*.jar"
          draft: false
          prerelease: false